micronaut:
  application:
    name: newsletter
  security:
    filter:
      enabled: false
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: sa
    schema-generate: NONE
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
#email:
#  from: "krishnay2k@yahoo.com"
#
#sendgrid:
#  api-key: "teset"
