micronaut:
  application:
    name: newsletter

---
micronaut:
  server:
    cors:
      enabled: true
---
micronaut:
  security:
    redirect:
      forbidden:
        url: 'forbidden'
      unauthorized:
        url: '/oauth/login/cognito'
    authentication: idtoken
#    oauth2:
#      clients:
#        cognito:
#          client-id: '${OAUTH_CLIENT_ID:xxx}'
#          client-secret: '${OAUTH_CLIENT_SECRET:yyy}'
#          openid:
#            issuer: 'https://cognito-idp.${COGNITO_REGION:eu-west-2}.amazonaws.com/${COGNITO_POOL_ID:12345}/'
    endpoints:
      logout:
        get-allowed: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: sa
    schema-generate: NONE
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
